### ISSUE TITLE
A question regarding licensing 

### ISSUE THREAD

**Issue by Woutah** [xmba15/obstacle_detection_stixelnet#2]
L.S.

I am sorry for contacting you this way, but I could not find a way to send you a private message.

I am a student at Leiden University in The Netherlands. For my bachelor thesis, I will be implementing an obstacle detection CNN for a small robot, and try to improve it for my use-case. As of now I am looking for a baseline and was wondering if I could use this repository for my research, since it has been put together so comprehensively. Of course I would be referencing and crediting you for your work (any additional requests regarding this would of course be more than welcome!). 

I look forward to hearing from you!

Kind regards,
Wouter

**Comment by xmba15** [comment]
Hi Wouter,

I have updated the MIT licence. Hope this repository can somehow help you with the thesis.

I would like to also share my thoughts on deployment on a small robot. Maybe you can also try semantic segmentation to segment the floor drivable area for the robot. A semantic segmentation model is also very straight forward. I just did a quick google and find this repo.
https://github.com/hellochick/Indoor-segmentation
But it really depends on your use case.

Best,
Ba Tran

**Comment by Woutah** [comment]
Hi Ba Tran,
Thank you for your quick response and for updating to the MIT license! Also thank you for your input; I considered (road) segmentation methods too, but right now, this seems more accessible and more suitable for my embedded/lightweight application. I might still try to experiment with such a model as well though! 

Kind regards,
Wouter
