### ISSUE TITLE
Question regarding graph cut and CRF 

### ISSUE THREAD

**Issue by sparshgarg23** [xmba15/obstacle_detection_stixelnet#3]
IN the original paper for stixelnet,the authors would use the output of stixel net and then send that as an input to a CRF for obstacle detection and then they would use the same output of stixelnet  as an input to a CRF.And then after that a graph cut algorithm would be applied.Will that be later on added to this project ,because I feel that this only predicts the stixels.

**Comment by xmba15** [comment]
@sparshgarg23 sorry for the late reply. this project only predicts the stixels.
Currently I do not have time to implement more than that, but open to discuss the post-process using CRF.
